//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mthembu_Funeral_Policy_App.Models
{
    using Mthembu_Funeral_Policy_App.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblFile
    {
        [Key]
        public int Id { get; set; }
        public string ID_Copy { get; set; }
        public string Death_Cert { get; set; }
        public string ContentType { get; set; }
        public byte[] Data { get; set; }

                 


    }
}
