//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Mthembu_Funeral_Policy_App.Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;

namespace Mthembu_Funeral_Policy_App.Models
{
    

    public partial class tlbAccount
    {
        public int id { get; set; }
       
        
        [Required(ErrorMessage = "This field is required.")]
        [DisplayName("Email")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [DisplayName("Password")]
        [DataType(DataType.Password)]
        [MinLength(8)]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [MinLength(8)]
        [DisplayName("Confirm Password")]
        public string ConfirmPassword { get; set; }
        public string ResetPasswordCode { get; set; }
        public Nullable<bool> Role { get; set; }
        
    }
    public class ResetPasswordModel
    {
        [Required(ErrorMessage = "New password required", AllowEmptyStrings = false)]
        [DataType(DataType.Password)]
        [MinLength(8)]
        [DisplayName("New Password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Compare("NewPassword", ErrorMessage = "New password and confirm password does not match")]
        [DisplayName("Confirm Password")]
        public string ConfirmPassword { get; set; }

        [Required]
        public string ResetCode { get; set; }
    }
    
}
