//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mthembu_Funeral_Policy_App.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Entity;
    using System.ComponentModel.DataAnnotations.Schema;
    using Mthembu_Funeral_Policy_App.Models;

    public partial class tlbClient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tlbClient()
        {
            this.tlbMembers = new HashSet<tlbMember>();
            this.tlbPayments = new HashSet<tlbPayment>();
            this.tlbPolicies = new HashSet<tlbPolicy>();
            this.tlbSpouses = new HashSet<tlbSpouse>();
            
            this.tlbBeneficiaries = new HashSet<tlbBeneficiary>();
        }
        [Key]
       
        public long Client_SA_ID_Number { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        [DisplayName("SA ID Number")]
        public long SA_ID { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        [DisplayName("First Name")]
        public string First_Name { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        [DisplayName("Last Name")]
        public string Last_Name { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        [DisplayName("Email")]
        [DataType(DataType.EmailAddress)]
        public string Email_Address { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        [DisplayName("Marital Status")]

        public string Marital_Status { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        [DisplayName("Gender")]
        public string Gender { get; set; }

        [Required(ErrorMessage = "This field is required.")]
        [DisplayName("Race")]
        public string Race { get; set; }

        [Required(ErrorMessage = "This field is required.")]
        [DisplayName("Cell Phone Number")]
        public long Cell_Phone { get; set; }

        [Required(ErrorMessage = "This field is required.")]
        [DisplayName("telephone Number")]
        public long Tell_Phone { get; set; }

        [Required(ErrorMessage = "This field is required.")]
        [DisplayName("City")]
        public string City { get; set; }

        [Required(ErrorMessage = "This field is required.")]
        [DisplayName("Home Address")]
        public string Home_Address { get; set; }

        [Required(ErrorMessage = "This field is required.")]
        [DisplayName("Postal Code")]
        public int Postal_Code { get; set; }

       
        
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tlbMember> tlbMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tlbPayment> tlbPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tlbPolicy> tlbPolicies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tlbSpouse> tlbSpouses { get; set; }
          


       
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tlbBeneficiary> tlbBeneficiaries { get; set; }


        
    }
}
