//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mthembu_Funeral_Policy_App.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    using System.Web.Mvc;

    public partial class tlbMessage
    {
        [Key]
        public int UserID { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        [DisplayName("Full Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        [DisplayName("Email")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        [DisplayName("Subject")]
        public string Subject { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        [DisplayName("Message")]
        public string Message { get; set; }
    }
}
