//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mthembu_Funeral_Policy_App.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tlbPolicy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tlbPolicy()
        {
            this.tlbPayments = new HashSet<tlbPayment>();
        }
        [Key]
        public int Policy_ID { get; set; }
        public Nullable<long> tlbClient_ID2 { get; set; }
        public Nullable<decimal> Policy_Cost { get; set; }
        public Nullable<decimal> Available_Amount { get; set; }
        public string Policy_Type { get; set; }
        public string Cover_Type { get; set; }
    
        public virtual tlbClient tlbClient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tlbPayment> tlbPayments { get; set; }
    }
}
