//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mthembu_Funeral_Policy_App.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    public partial class tlbSpouse
    {
        [Key]
        public long id { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        [DisplayName("SA ID Number")]
        public long Spouse_SA_ID_Number { get; set; }
        public Nullable<long> tlbClient_ID { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        [DisplayName("First Name")]
        public string Spouse_First_Name { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        [DisplayName("Last Name")]
        public string Spouse_Last_Name { get; set; }
    
        public virtual tlbClient tlbClient { get; set; }
    }
}
